version: "3.6"
services:
  prod:
    image: tons/whoami-go
    build: .
    ports:
      - 8080:8080

  test:
    build:
      context: .
      target: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'go test -v ./test'

  dev:
    build:
      context: .
      target: build
    ports:
      - 8080:8080
    volumes:
      - .:/src
    command: reflex -r "\.go$$" -s -- sh -c "go run ."
