environments:
  dev:
    values:
      - kubeContext: default
      - name: whoami-go
      - hostname: whoami-go.dev.fitfit.dk
      - certIssuer: letsencrypt-staging
      - replicaCount: 1

  prod:
    values:
      - kubeContext: default
      - name: whoami-go
      - hostname: whoami-go.fitfit.dk
      - certIssuer: letsencrypt-prod
      - replicaCount: 2

  feature:
    values:
      - kubeContext: default
      - name: whoami-go-{{ .Environment.Name }}-{{ requiredEnv "FEATURE_TAG" }}
      - hostname: whoami-go-{{ requiredEnv "FEATURE_TAG" }}.fitfit.dk
      - certIssuer: letsencrypt-staging
      - replicaCount: 1

releases:
  - name: "{{ .Values.name }}"
    namespace: whoami-go-{{ .Environment.Name }}
    chart: helm/
    kubeContext: "{{ .Values.kubeContext }}"
    values:
      - ingress:
          enabled: true
          hostname: {{ .Values.hostname }}
          certIssuer: {{ .Values.certIssuer }}
      - replicaCount: {{ .Values.replicaCount }}

helmDefaults:
  recreatePods: true
