environments:
  dev:
    values:
      - kubeContext: nuc
      - name: whoami-go
      - host: whoami-go.dev.fitfit.dk

  prod:
    values:
      - kubeContext: nuc
      - name: whoami-go
      - host: whoami-go.fitfit.dk

  feature:
    values:
      - kubeContext: nuc
      - name: whoami-go-{{ .Environment.Name }}-{{ requiredEnv "IMAGE_TAG" }}
      - host: whoami-go-{{ requiredEnv "IMAGE_TAG" }}.fitfit.dk

releases:
  - name: "{{ .Values.name }}"
    namespace: whoami-go-{{ .Environment.Name }}
    chart: helm/
    kubeContext: "{{ .Values.kubeContext }}"
    values:
      - image:
          tag: '{{ requiredEnv "IMAGE_TAG" }}'
      - ingress:
          hosts:
            - host: {{ .Values.host }}
              paths:
                - path: /
