environments:
  dev:
    values:
#      - kubeContext: nuc
      - kubeContext: arn:aws:eks:eu-central-1:767224633206:cluster/instance-cluster-test
      - name: whoami-go
      - hostname: dev.whoami-go.im.dhis2.org
      - certIssuer: cert-issuer-prod
      - replicaCount: 1

  prod:
    values:
      - kubeContext: nuc
      - name: whoami-go
      - hostname: whoami-go.fitfit.dk
      - certIssuer: letsencrypt-prod
      - replicaCount: 2

  feature:
    values:
      - kubeContext: nuc
      - name: whoami-go-{{ .Environment.Name }}-{{ requiredEnv "FEATURE_TAG" }}
      - hostname: whoami-go-{{ requiredEnv "FEATURE_TAG" }}.fitfit.dk
      - certIssuer: letsencrypt-staging
      - replicaCount: 1

releases:
  - name: "{{ .Values.name }}"
    namespace: whoami-go-{{ .Environment.Name }}
    chart: ./charts/whoami-go/
    kubeContext: "{{ .Values.kubeContext }}"
    values:
      - ingress:
          enabled: true
          hostname: {{ .Values.hostname }}
          certIssuer: {{ .Values.certIssuer }}
      - replicaCount: {{ .Values.replicaCount }}

helmDefaults:
  recreatePods: true
