environments:
  dev:
    values:
      - kubeContext: nuc
      - name: whoami-go
      - host: whoami-go.dev.fitfit.dk
      - certIssuer: letsencrypt-staging

  prod:
    values:
      - kubeContext: nuc
      - name: whoami-go
      - host: whoami-go.fitfit.dk
      - certIssuer: letsencrypt-prod

  feature:
    values:
      - kubeContext: nuc
      - name: whoami-go-{{ .Environment.Name }}-{{ requiredEnv "FEATURE_TAG" }}
      - host: whoami-go-{{ requiredEnv "FEATURE_TAG" }}.fitfit.dk
      - certIssuer: letsencrypt-staging

releases:
  - name: "{{ .Values.name }}"
    namespace: whoami-go-{{ .Environment.Name }}
    chart: helm/
    kubeContext: "{{ .Values.kubeContext }}"
    values:
      - ingress:
          enabled: true
          hostname: {{ .Values.host }}
          certIssuer: {{ .Values.certIssuer }}

helmDefaults:
  recreatePods: true
